# Generated by Django 4.0.6 on 2022-07-11 08:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('centros', '0002_alter_bono_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bono',
            name='agente',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='bono',
            name='centro',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='bono',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 11, 8, 29, 0, 622543, tzinfo=utc)),
        ),
    ]
